### ISSUE TITLE
請問如何在Ubuntu下面編譯

### ISSUE THREAD

**Issue by kousyougi** [pexcn/openwrt-ipt2socks#1]
請問如何在Ubuntu下面編譯可以在 OpenWrt X86-64 下面執行的ipt2socks。

是把抓下來的東西丟到OpenwrtSDK/packages/下面，然後執行 'make package/ipt2socks/{clean,compile} V=99' 嗎？

謝謝

**Comment by pexcn** [comment]
我通常使用 CI 來自動編譯，你可以參考一下這個腳本：https://github.com/openwrt-dev/feeds/blob/master/build.sh

**Comment by kousyougi** [comment]
謝謝 我試看看
