### ISSUE TITLE
1.1.2版编译报错

### ISSUE THREAD

**Issue by QiuSimons** [pexcn/openwrt-ipt2socks#4]
1.1.1可以编译通过，1.1.2 报错。（x86 和 arm都报错了

**Comment by pexcn** [comment]
我没有测试，可能和 https://github.com/zfl9/ipt2socks/issues/22#issuecomment-629752649 有关，等待上游更新吧

**Comment by pexcn** [comment]
https://github.com/pexcn/openwrt-ipt2socks/commit/01ddc52eb8bf2a3bc627178ea4643037e3c6f609
